ncamp16-team3/ncamp16-team3

iz/src/main/resources/templates/findId.html, iz/src/main/resources/templates/findIdResult.html, iz/src/main/resources/templates/findPw.html, iz/src/main/resources/templates/findPwResult.html, iz/src/main/resources/templates/register.html
=> [ADD] 로그인/회원가입 index 제외

iz/src/main/resources/templates/index.html
=> [ADD] index

iz/src/main/java/com/iz/controller/AlarmController.java, iz/src/main/java/com/iz/controller/BoardController.java, iz/src/main/java/com/iz/controller/CommentController.java, iz/src/main/java/com/iz/controller/JobController.java, iz/src/main/java/com/iz/controller/LoginController.java, iz/src/main/java/com/iz/controller/StressController.java, iz/src/main/java/com/iz/entity/AlarmComment.java, iz/src/main/java/com/iz/entity/AlarmPopular.java, iz/src/main/java/com/iz/entity/AlarmStress.java, iz/src/main/java/com/iz/entity/Board.java, iz/src/main/java/com/iz/entity/Comment.java, iz/src/main/java/com/iz/entity/Job.java, iz/src/main/java/com/iz/entity/Stress.java, iz/src/main/java/com/iz/entity/User.java, iz/src/main/resources/static/css/mainStyle.css
=> [ADD] 프로젝트 구조 추가

iz/src/main/java/com/iz/controller/BoardController.java, iz/src/main/java/com/iz/controller/JobController.java, iz/src/main/java/com/iz/controller/LoginController.java, iz/src/main/java/com/iz/controller/UserController.java, iz/src/main/java/com/iz/entity/AlarmJob.java, iz/src/main/java/com/iz/entity/AlarmPopular.java, iz/src/main/java/com/iz/entity/AlarmStress.java, iz/src/main/java/com/iz/entity/Board.java, iz/src/main/java/com/iz/entity/Comment.java, iz/src/main/java/com/iz/entity/Job.java, iz/src/main/java/com/iz/entity/Stress.java, iz/src/main/java/com/iz/entity/User.java
___
```java
@Controller
@RequestMapping("/board")
public class BoardController {
}
```
```java
@Controller
@RequestMapping("/job")
public class JobController {
}
```
```java
@Controller
public class LoginController {
@GetMapping("/login")
public String login() {
return "index";
}
@GetMapping("/logout")
public String logout() {
return "redirect:/";
}
}
```
```java
@Controller
@RequestMapping("/user")
public class UserController {
@GetMapping("/update")
public String update() {
return "update";
}
@GetMapping("/checkPwd")
public String checkPwd() {
return "checkPwd";
}
}
```
```java
@Data
public class AlarmComment {
private int alarm_id;
private String member_id;
private int board_type;
private int board_id;
private String title;
private String alarm_date;
}
```
테이블엔 있는데 엔티티엔 없는것같아서 추가했습니다 …
=> [ADD] entity와 controller 추가/수정

iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/community.html, iz/src/main/resources/templates/myBoad.html, iz/src/main/resources/templates/popularityCommunity.html, iz/src/main/resources/templates/postDetail.html, iz/src/main/resources/templates/postForm.html
community, myBoad, populaityCommunity, postDetail, postForm html 1차 완성.
=> [ADD]게시판 HTML 화면 1차구현

iz/build.gradle, iz/src/main/java/com/iz/config/AppConfig.java, iz/src/main/java/com/iz/controller/LoginController.java, iz/src/main/java/com/iz/controller/UserController.java, iz/src/main/java/com/iz/entity/User.java, iz/src/main/java/com/iz/mapper/UserMapper.java, iz/src/main/resources/application.properties, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/register.html
mybatis, mysql 라이브러리 추가.
application.properties
mybatis, mysql 설정 추가.
=> [ADD] 회원가입 기능 구현 초안

iz/build.gradle, iz/src/main/java/com/iz/config/DataSourceConfig.java, iz/src/main/java/com/iz/config/MyBatisConfig.java, iz/src/main/java/com/iz/controller/DBConnectionTestController.java, iz/src/main/java/com/iz/repository/UserMapper.java, iz/src/main/java/com/iz/service/DBConnectionTestService.java, iz/src/main/resources/application.properties
=> [FEAT] HikariCP 연결 및 테스트 완료

iz/src/main/java/com/iz/controller/LoginController.java, iz/src/main/java/com/iz/controller/UserController.java, iz/src/main/java/com/iz/repository/UserMapper.java, iz/src/main/java/com/iz/service/LoginService.java, iz/src/main/resources/application.properties, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/register.html
=> [ADD] 로그인 구현/회원가입 수정

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/board/community.html
=> [ADD]자유/하소연 게시판 리스트 출력 진행중

iz/src/main/resources/templates/header.html
=> [FEAT]:header a태그 기능 추가

iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/repository/UserMapper.java, iz/src/main/java/com/izikgram/user/service/UserService.java, iz/src/main/resources/application.properties, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findIdResult.html, iz/src/main/resources/templates/user/findPw.html, iz/src/main/resources/templates/user/findPwResult.html, iz/src/main/resources/templates/user/register.html
=> [FEAT] 아이디/비밀번호 찾기 구현

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/postForm.html
[ADD}자유/하소연 게시글 작성 기능 구현이요. 삭제는 아직입니다?
=> Shindongeok

iz/src/main/resources/static/css/default.css, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findIdResult.html, iz/src/main/resources/templates/user/findPw.html, iz/src/main/resources/templates/user/findPwResult.html, iz/src/main/resources/templates/user/register.html
```css
/* PC에서 모바일 크기로 고정 */
@media screen and (min-width: 769px) {
.mobile-container {
width: 600px;
margin: 0 auto;
background: white;
box-shadow: 0 0 10px rgba(0,0,0,0.1);
min-height: 100vh;
}
}
/* 모바일에서는 전체 너비 사용 */
@media screen and (max-width: 768px) {
.mobile-container {
width: 100%;
background: white;
min-height: 100vh;
}
}
html {
background-color: #f0f0f0;
}
```
=> [FEAT] CSS 수정

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/myBoad.html, iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html
=> [ADD]자유/하소연 글 상세보기 구현중..

iz/src/main/java/com/izikgram/user/controller/LoginController.java, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/user/register.html
=> [FEAT] 로그인/회원가입 수정

iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/job/scrap.html
=> [ADD]: 헤더 초안

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/main/controller/MainController.java, iz/src/main/java/com/izikgram/main/repository/MainMapper.java, iz/src/main/java/com/izikgram/main/service/MainService.java, iz/src/main/resources/application.properties, iz/src/main/resources/static/css/mainStyle.css, iz/src/main/resources/templates/main/main.html
=> [ADD] 메인페이지 인기게시글 기능 구현

iz/build.gradle, iz/src/main/java/com/izikgram/global/config/CustomLoginSuccessHandler.java, iz/src/main/java/com/izikgram/global/config/CustomUserDetails.java, iz/src/main/java/com/izikgram/global/config/CustomUserDetailsService.java, iz/src/main/java/com/izikgram/global/config/SecurityConfig.java, iz/src/main/java/com/izikgram/main/controller/MainController.java, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/entity/User.java, iz/src/main/java/com/izikgram/user/service/UserService.java, iz/src/main/resources/application.properties, iz/src/main/resources/templates/user/mypage.html, iz/src/main/resources/templates/user/update.html
[REFACTOR] UserController, UserService, 마이페이지 HTML
=> [ADD] 스프링 시큐리티 로그인 구현(인코딩)

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html
=> [FEAT]게시글 작성 수정 및 게시글 수정 진행중..

iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/job/hire.html, iz/src/main/resources/templates/job/scrap.html
[FEAT]: scrap, hire, header 코드 수정
=> [FEAT]: scrap, hire, header 코드 수정

iz/.gitignore, iz/build.gradle, iz/src/main/java/com/izikgram/global/config/CustomUserDetails.java, iz/src/main/java/com/izikgram/global/config/SecurityConfig.java, iz/src/main/java/com/izikgram/user/controller/LoginController.java, iz/src/main/resources/templates/user/mypage.html
=> [ADD] Spring Security 로그인실패 핸들러 추가

iz/src/main/java/com/izikgram/global/config/SecurityConfig.java, iz/src/main/resources/templates/user/register.html
```java
.requestMatchers("/css/**", "/js/**", "/images/**", "/static/**").permitAll() // 정적 리소스 허용
```
```java
"/user/checkId/**"
```
=> [FIX] SecurityConfig 정적 리소스 추가

iz/build.gradle, iz/src/main/java/com/izikgram/global/config/RedisConfig.java, iz/src/main/java/com/izikgram/global/config/SecurityConfig.java, iz/src/main/java/com/izikgram/user/controller/AuthController.java, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/repository/UserMapper.java, iz/src/main/java/com/izikgram/user/service/AuthService.java, iz/src/main/java/com/izikgram/user/service/SmsService.java, iz/src/main/java/com/izikgram/user/service/UserService.java, iz/src/main/resources/application.properties, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/register.html
sms 관련 api키 추가
redis 설정 추가
coolsms 추가
redis 추가
=> [ADD] sms 인증 구현 초안

.idea/workspace.xml, iz/src/main/java/com/izikgram/main/controller/MainController.java, iz/src/main/resources/static/js/mainScript.js, iz/src/main/resources/templates/main/main.html
[FIX] 메인페이지에서 사이드바 css 적용안되는 것 해결, 메인페이지 security 적용
=> [FIX] 메인페이지에서 사이드바 css 적용안되는 것 해결, 메인페이지 security 적용

iz/src/main/java/com/izikgram/global/security/CustomLoginSuccessHandler.java, iz/src/main/java/com/izikgram/global/security/CustomUserDetails.java, iz/src/main/java/com/izikgram/global/security/CustomUserDetailsService.java, iz/src/main/java/com/izikgram/global/security/SecurityConfig.java, iz/src/main/java/com/izikgram/job/controller/JobController.java, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/entity/User.java, iz/src/main/java/com/izikgram/user/repository/UserMapper.java, iz/src/main/resources/templates/user/mypage.html, iz/src/main/resources/templates/user/update.html
[FEAT] 매퍼 getUserInfo()에서 iz_member정보 + stress_num 쿼리 수정
=> [FEAT] 마이페이지 게이지 기능 구현

iz/src/main/java/com/izikgram/global/security/SecurityConfig.java, iz/src/main/java/com/izikgram/user/controller/AuthController.java, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findIdResult.html
=> [FIX] 아이디찾기 수정

iz/src/main/resources/application.properties, iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/job/hire.html, iz/src/main/resources/templates/job/scrap.html
[FEAT]: 헤더 로고 추가 및 로고클릭시 메인이동,scrap,hire코드수정
=> [FEAT]: 헤더 로고 추가 및 로고클릭시 메인이동,scrap,hire코드수정

iz/build.gradle, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/user/findId.html
=> [FEAT] sms 인증 타이머 추가 / build.gradle 중복 제거

iz/build.gradle, iz/src/main/java/com/izikgram/global/config/JasyptConfig.java, iz/src/main/resources/application.properties, iz/src/test/java/com/izikgram/global/config/JasyptConfigTest.java
jasypt 라이브러리 추가
```
-Djasypt.encryptor.password=환경변수
```
=> [ADD] Jasypt로 application.properties 암호화

iz/src/main/java/com/izikgram/job/controller/JobController.java, iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/job/hire.html, iz/src/main/resources/templates/job/scrap.html, iz/src/main/resources/templates/main/alarm.html, iz/src/main/resources/templates/main/main.html
alarm,header, hire, main, scrap, jobController 코드 수정
=> [FEAT]: alarm,header, hire, main, scrap, jobController 코드 수정

iz/src/main/java/com/izikgram/user/controller/AuthController.java, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/repository/UserMapper.java, iz/src/main/java/com/izikgram/user/service/UserService.java, iz/src/main/resources/templates/user/findId.html
=> [FEAT] 아이디찾기 수정

iz/src/main/resources/templates/header.html
=> [FEAT]: header 위치 수정

iz/src/main/java/com/izikgram/global/security/CustomLoginSuccessHandler.java, iz/src/main/java/com/izikgram/global/security/CustomUserDetails.java, iz/src/main/java/com/izikgram/global/security/CustomUserDetailsService.java, iz/src/main/java/com/izikgram/user/entity/Stress.java, iz/src/main/java/com/izikgram/user/repository/UserMapper.java, iz/src/main/java/com/izikgram/user/service/UserService.java, iz/src/main/resources/templates/user/mypage.html, iz/src/main/resources/templates/user/update.html
[FIX] 회원가입 후 로그인 시, stress_num 값 문제 해결
=> [REFACTOR] 회원가입 관련 Service, Handler 수정

iz/src/main/java/com/izikgram/global/security/SecurityConfig.java, iz/src/main/java/com/izikgram/user/controller/AuthController.java, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/repository/UserMapper.java, iz/src/main/java/com/izikgram/user/service/UserService.java, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findPw.html, iz/src/main/resources/templates/user/findPwResult.html, iz/src/main/resources/templates/user/register.html
=> [FEAT] 아이디찾기/비밀번호찾기/로그인/회원가입 모달 수정

iz/src/main/resources/templates/user/register.html
=> [FIX] 회원가입 수정

iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findIdResult.html, iz/src/main/resources/templates/user/findPw.html, iz/src/main/resources/templates/user/findPwResult.html, iz/src/main/resources/templates/user/register.html
=> [FEAT] 로고 css 수정/href 추가

iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findPw.html, iz/src/main/resources/templates/user/register.html
=> [FEAT] 휴대폰번호 입력제한

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/controller/BoardRestController.java, iz/src/main/java/com/izikgram/board/controller/CommentController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/myBoad.html, iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html
BoardMapper 쿼리 수정 및 게시판 페이지에 헤더 적용 및 유저객체 가져와서 사용하는거  수정??
=> [ADD]게시판페이지 해더 붙임 및 게시판 member_id가져오는거 수정.

iz/src/main/java/com/izikgram/job/controller/JobController.java, iz/src/main/resources/static/css/mainStyle.css, iz/src/main/resources/templates/footer.html, iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/job/scrap.html, iz/src/main/resources/templates/user/mypage.html
=> [FEAT] 헤더, 푸터 수정

iz/src/main/java/com/izikgram/main/controller/MainController.java, iz/src/main/java/com/izikgram/user/controller/UserController.java
⚠️String으로 리턴받아서 html로 보내는건 앞에 '/' 제거해주세요!⚠️
> return "/main/main"; -> return "main/main";
=> [FIX] 로그인 수정/ return '/' 제거

iz/src/main/resources/templates/main/main.html
=> [FIX] header 경로 수정

iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/myBoad.html, iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html, iz/src/main/resources/templates/job/hire.html, iz/src/main/resources/templates/job/scrap.html, iz/src/main/resources/templates/main/alarm.html, iz/src/main/resources/templates/main/main.html, iz/src/main/resources/templates/user/mypage.html
=> [FEAT] 헤더, 푸터 앞 "/"제거

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/controller/CommentController.java, iz/src/main/java/com/izikgram/board/entity/BoardDto.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/myBoard.html, iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html
=> [FEAT] :  인기게시판 조회

iz/src/main/java/com/izikgram/alarm/controller/AlarmController.java, iz/src/main/java/com/izikgram/alarm/entity/AlarmComment.java, iz/src/main/java/com/izikgram/alarm/entity/AlarmType.java, iz/src/main/java/com/izikgram/alarm/repository/AlarmMapper.java, iz/src/main/java/com/izikgram/alarm/repository/SseEmitterRepository.java, iz/src/main/java/com/izikgram/alarm/service/AlarmService.java, iz/src/main/java/com/izikgram/alarm/service/SseEmitterService.java, iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/main/alarm.html
DB에서 알림 삭제 
-> 중복 알림 문제로 isRead 컬럼 추가 update로 변경
=> [FEAT] 인기게시글 알람 1차 구현

iz/src/main/resources/application.properties, iz/src/test/java/com/izikgram/global/config/JasyptConfigTest.java
=> [FIX] api 암호화/신규발급

iz/src/main/resources/application.properties, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findPw.html, iz/src/main/resources/templates/user/findPwResult.html, iz/src/main/resources/templates/user/register.html
로그인/회원가입/아이디찾기/비밀번호찾기
```properties
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true
spring.thymeleaf.cache=false
```
=> [FEAT] 로그인관련 css수정/타임리프 설정 추가

iz/src/main/resources/templates/user/register.html
=> [FEAT] 사람인api 코드표대로 register.html 수정

iz/src/main/java/com/izikgram/job/controller/JobController.java, iz/src/main/java/com/izikgram/job/repository/JobMapper.java, iz/src/main/java/com/izikgram/job/service/JobService.java, iz/src/main/resources/static/js/hireScript.js, iz/src/main/resources/templates/job/hire.html
=> [FEAT]사람인 API(채용공고 페이지) 기능 완성

iz/build.gradle, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/entity/User.java, iz/src/main/resources/templates/user/register.html
```java
@Pattern(regexp = "[a-zA-Z0-9]{6,20}", message = "6~20자 사이의 영문대소문자와 숫자로만 입력해주세요")
private String member_id;
@Pattern(regexp = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,15}$", message = "비밀번호는 8~15자 사이이며, 영문대소문자와 숫자가 필수입니다")
private String password;
@Pattern(regexp = "[가-힣]{2,5}", message = "2~5글자 사이의 한글로 적어주세요")
private String name;
@Pattern(regexp = "[0-9]{10,11}", message = "10~11글자 사이의 숫자만 입력해주세요")
private String phone_num;
@Email(message = "이메일형식으로 적어주세요")
private String email;
```
=> [FEAT] 회원가입시 validation 기능 추가

iz/src/main/resources/templates/user/register.html, iz/src/test/java/com/izikgram/global/config/JasyptConfigTest.java
=> [CHORE] register 주석/오타 수정

iz/Dockerfile, iz/docker-compose.yml, iz/src/main/resources/application.properties, iz/src/main/resources/templates/user/register.html, iz/src/test/java/com/izikgram/global/config/JasyptConfigTest.java
=> [ADD] main 브랜치로 ci/cd

iz/src/main/resources/templates/job/hire.html, iz/src/main/resources/templates/main/main.html
=> [CHORE] 모바일 최적화

iz/src/main/java/com/izikgram/draw/controller/DrawController.java, iz/src/main/java/com/izikgram/draw/service/DrawGame.java, iz/src/main/java/com/izikgram/global/security/SecurityConfig.java, iz/src/main/resources/templates/draw.html, iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/user/chat.html
=> [FEAT]제비뽑기 기능 추가,  헤더/챗봇 코드변경

iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/resources/static/css/default.css, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findPw.html, iz/src/main/resources/templates/user/findPwResult.html, iz/src/main/resources/templates/user/register.html
=> [CHORE] CSS 수정

iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/entity/PasswordDTO.java, iz/src/main/resources/static/css/default.css, iz/src/main/resources/templates/user/findIdResult.html, iz/src/main/resources/templates/user/findPwResult.html
=> [FIX] 비밀번호 재설정 유효성검증 수정

iz/src/main/resources/static/css/default.css, iz/src/main/resources/templates/user/register.html
=> [CHORE] register css 수정

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/controller/BoardRestController.java, iz/src/main/java/com/izikgram/board/controller/CommentController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/feelMyBoard.html, iz/src/main/resources/templates/board/myBoard.html, iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html, iz/src/main/resources/templates/board/whiningMyBoard.html
[FIX]  게시판 기능 동작 가능하게 했습니다 안되면 말해주세요 ㅠ..
=>  [FIX] 게시판 기능 가능하게 수정..

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/postForm.html
글작성 페이지 안나오는거 postForm.html 수정했습니다.
=>  [FIX] 글작성 html 수정.

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/controller/BoardRestController.java, iz/src/main/java/com/izikgram/board/controller/CommentController.java, iz/src/main/resources/templates/board/community.html
=>  [FIX] 게시판 html수정

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/feelMyBoard.html, iz/src/main/resources/templates/board/myBoard.html, iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html, iz/src/main/resources/templates/board/whiningMyBoard.html
=>  [FIX] 게시판 html 크기 수정.

iz/src/main/java/com/izikgram/chat/config/ChatConfig.java, iz/src/main/java/com/izikgram/chat/controller/ChatController.java, iz/src/main/java/com/izikgram/chat/dto/ChatResponse.java, iz/src/main/java/com/izikgram/chat/dto/Message.java, iz/src/main/java/com/izikgram/chat/service/ChatService.java, iz/src/main/java/com/izikgram/global/config/AppConfig.java, iz/src/main/resources/application.properties, iz/src/main/resources/templates/user/chat.html
[ADD] chat 관련 dto 추가
[FEAT] 챗봇 대화 구현 (미완성)
=> [FEAT] 챗봇 대화 구현 (미완성)

iz/src/main/resources/static/js/mainScript.js
=> [CHORE] 스트레스 지수 툴팁 토글 형태로 변경

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/controller/BoardRestController.java, iz/src/main/java/com/izikgram/board/controller/CommentController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/board/community.html
[FEAT] : 댓글,최신순,이직해순 조회 구현  무한스크롤같이하는거 계속 해보긴할게요....
=> [FEAT] : 댓글,최신순,이직해순 조회 구현

iz/src/main/java/com/izikgram/user/controller/AuthController.java, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/java/com/izikgram/user/dto/PasswordDTO.java, iz/src/main/resources/templates/index.html, iz/src/main/resources/templates/user/findId.html, iz/src/main/resources/templates/user/findIdResult.html, iz/src/main/resources/templates/user/findPw.html, iz/src/main/resources/templates/user/findPwResult.html, iz/src/main/resources/templates/user/register.html
=> [CHORE] 로그제거 및 css 수정

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java
[FIX] : 인기게시판 수정
******좋아요 눌렀을때 5개 이상이면 인기게시판으로  수정
=>  [FIX] : 인기게시판 수정

iz/src/main/java/com/izikgram/chat/controller/ChatController.java, iz/src/main/java/com/izikgram/chat/service/ChatService.java, iz/src/main/java/com/izikgram/user/entity/Stress.java, iz/src/main/java/com/izikgram/user/repository/UserMapper.java, iz/src/main/resources/templates/user/chat.html
=> [ADD] 챗봇 구현, 스트레스 값 저장됨

iz/src/main/java/com/izikgram/global/security/CustomLoginSuccessHandler.java, iz/src/main/java/com/izikgram/global/security/CustomUserDetailsService.java, iz/src/main/java/com/izikgram/user/controller/UserController.java, iz/src/main/resources/templates/user/updatePw.html
=> [FEAT] 비밀번호 수정 validation 추가

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html
[FIX] 인기게시판 수정
[FIX] 게시글 수정 페이지 모달창 수정
[FIX] 상세페이지 모달창 수정
=> [FIX] 인기게시판 수정

iz/src/main/resources/templates/main/main.html
=> [FIX] 전광판 css 수정

iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/postForm.html
[ADD] community.html : css수정
[ADD] community.html : css수정
=> [ADD] community.html : css수정

iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/popularityCommunity.html
=> [FIX] 게시글 css 수정

iz/src/main/resources/templates/board/community.html
=> [FIX] 자유게시판 1개이상 안뜨는문제 수정

iz/src/main/resources/templates/board/postDetail.html
[ADD] postDetail.html css수정 모달창
=> [ADD] postDetail.html css수정 모달창

iz/src/main/resources/templates/board/myBoard.html, iz/src/main/resources/templates/main/alarm.html, iz/src/main/resources/templates/user/accountManagement.html, iz/src/main/resources/templates/user/mypage.html
[CHORE] 계정관리/알람/내게시글/마이페이지 css 수정
=> [CHORE] 계정관리/알람/내게시글/마이페이지 css 수정

iz/src/main/resources/static/css/register.css, iz/src/main/resources/templates/user/accountManagement.html, iz/src/main/resources/templates/user/mypage.html, iz/src/main/resources/templates/user/register.html, iz/src/main/resources/templates/user/update.html
[CHORE] 계정관리/마이페이지/회원가입/정보수정 css 수정
=> [CHORE] 계정관리/마이페이지/회원가입/정보수정 css 수정

iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/postDetail.html
[ADD] postDetail.html/js 댓글 ,수정??
=> [ADD] postDetail.html/js 댓글 ,수정??

iz/src/main/resources/templates/header.html
=> [CHORE] 헤더 아이콘 변경

iz/src/main/resources/templates/board/postDetail.html
=> [ADD] postDetail.thml 모달창 수정

iz/src/main/resources/static/js/chatScript.js
=> [FIX] 챗봇 js 중복입력 수정

iz/src/main/java/com/izikgram/user/controller/AuthController.java
=> [CHORE] sms인증 주석 해제

iz/src/main/resources/templates/board/postDetail.html
[FIX] 게시글 상세보기 댓글 input창 길이 수정
=> [FIX] 게시글 상세보기 댓글 input창 길이 수정

iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java
=> [FIX] 인기게시판 3번째 수정이요..

iz/src/main/resources/templates/board/postFormModify.html
[FIX] postFormModify.html 업뎃 안되는거 다시 수정
=> [FIX] postFormModify.html 수정

iz/src/main/resources/templates/board/freeMyBoard.html, iz/src/main/resources/templates/board/myBoard.html, iz/src/main/resources/templates/board/whiningMyBoard.html
=> [FIX] 내 게시물 댓글 아이콘 수정.

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/controller/BoardRestController.java, iz/src/main/java/com/izikgram/board/controller/CommentController.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/postDetail.html
=> [CHORE] : 필요없는 log.info 삭제

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/static/js/likeDisLike.js, iz/src/main/resources/templates/board/postDetail.html
=> [FIX] 게시판 상세보기 따봉 수정

iz/src/main/resources/templates/header.html
=> [CHORE] 헤더 아이콘 변경 및 코드 수정

iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html
[CHORE] : postDetail, postForm, postFormModify.html 모달창 다시수정?
=> [CHORE] : postDetail, postForm, postFormModify.html 모달창 다시수정?

iz/src/main/resources/static/js/likeDisLike.js, iz/src/main/resources/templates/board/postDetail.html
=> [FIX] 따봉 또잉또잉

iz/src/main/resources/static/css/register.css, iz/src/main/resources/templates/main/main.html
=> [FIX] timepicki css 수정

iz/src/main/java/com/izikgram/main/service/MainService.java, iz/src/main/resources/templates/main/main.html
=> [FIX] main 시간설정 수정

iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html
=> [CHORE] : 인기게시판 css 수정

iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html
=> [CHORE] : 상세게시글 댓글 css 수정

iz/src/main/resources/templates/board/popularityCommunity.html
=> [CHORE] : 인기게시글 css수정

iz/src/main/resources/static/js/chatScript.js, iz/src/main/resources/templates/user/chat.html
=> [FIX] chat 편의성/css 개선

iz/src/main/resources/templates/board/postDetail.html
=> [CHORE] : 상세게시글 댓글 CSS수정

iz/src/main/resources/static/js/chatScript.js, iz/src/main/resources/templates/user/chat.html
=> [FIX] chat 편의성/css 개선2

iz/src/main/resources/static/js/postDetail.js
=> [CHORE] : 상세 게시글 댓글수정 부분 수정

iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/postDetail.html
[CHORE] : 상세 게시글 댓글 css 부분 수정2
=> [CHORE] : 상세 게시글 댓글 css 부분 수정2

iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/user/chat.html, iz/src/main/resources/templates/user/register.html
[FIX] chat 편의성/css 개선, 푸터 트랜지션 추가
=> [FIX] chat 편의성/css 개선, 푸터 트랜지션 추가

iz/src/main/resources/static/js/postDetail.js
[CHORE] : 상세 게시글 댓글 css 부분 수정3
=> [CHORE] : 상세 게시글 댓글 css 부분 수정3

iz/src/main/java/com/izikgram/draw/controller/DrawController.java, iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/roulette.html
=> [FEAT] 룰렛 기능 추가

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/controller/BoardRestController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/board/community.html
=> [FEAT] 자유/하소연게시판 무한스크롤

iz/src/main/java/com/izikgram/board/controller/BoardController.java, iz/src/main/java/com/izikgram/board/repository/BoardMapper.java, iz/src/main/java/com/izikgram/board/service/BoardService.java, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/freeMyBoard.html, iz/src/main/resources/templates/board/whiningMyBoard.html
=> [FEAT] 내게시글(자유/하소연)무한스크롤

iz/src/main/resources/templates/board/freeMyBoard.html, iz/src/main/resources/templates/board/whiningMyBoard.html
=> [FIX] 내게시글(자유/하소연)무한스크롤 수정

iz/src/main/resources/templates/board/community.html
=> [FIX] 자유/하소연 무한스크롤 수정2

iz/src/main/java/com/izikgram/board/controller/BoardRestController.java, iz/src/main/java/com/izikgram/chat/controller/ChatController.java, iz/src/main/java/com/izikgram/chat/service/ChatService.java, iz/src/main/java/com/izikgram/main/service/MainService.java, iz/src/main/resources/templates/board/community.html, iz/src/main/resources/templates/board/freeMyBoard.html, iz/src/main/resources/templates/board/myBoard.html, iz/src/main/resources/templates/board/popularityCommunity.html, iz/src/main/resources/templates/board/postDetail.html, iz/src/main/resources/templates/board/postForm.html, iz/src/main/resources/templates/board/postFormModify.html, iz/src/main/resources/templates/board/whiningMyBoard.html, iz/src/main/resources/templates/draw.html, iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/job/hire.html, iz/src/main/resources/templates/job/scrap.html, iz/src/main/resources/templates/main/alarm.html, iz/src/main/resources/templates/main/main.html, iz/src/main/resources/templates/user/accountManagement.html, iz/src/main/resources/templates/user/chat.html, iz/src/main/resources/templates/user/checkPwd.html, iz/src/main/resources/templates/user/mypage.html, iz/src/main/resources/templates/user/update.html, iz/src/main/resources/templates/user/updatePw.html
=> [CHORE] 전체 폰트 통일 및 css 전체 수정

iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/postDetail.html
=> [DEL] 상세게시글 댓글

iz/src/main/resources/static/js/postDetail.js, iz/src/main/resources/templates/board/postDetail.html
=> [CHORE] 상세게시글 댓글 css수정

iz/src/main/resources/templates/roulette.html
=> [CHORE] 룰렛 효과추가

iz/docker-compose.yml, iz/src/main/resources/templates/main/main.html
=> [CHORE] main css 수정

iz/docker-compose.yml
=> [CHORE] docker-compose.yml 수정

iz/src/main/resources/templates/roulette.html
=> [CHORE] 룰렛 전구 위치 수정

iz/src/main/java/com/izikgram/global/config/CorsConfig.java
=> [FIX] cors 수정

iz/src/main/java/com/izikgram/global/config/CorsConfig.java
=> [FIX] CorsConfig https 추가

iz/src/main/resources/static/js/mainScript.js
=> [CHORE] mainScript.js 수정

iz/src/main/resources/templates/roulette.html
=> [CHORE] 모달 수정

iz/src/main/resources/templates/header.html, iz/src/main/resources/templates/user/checkPwd.html
=> [FIX] 비밀번호확인/룰렛 css 수정

iz/src/main/resources/templates/user/register.html
=> [FIX] 기본달력 제거

iz/src/main/resources/static/js/mainScript.js, iz/src/main/resources/templates/main/main.html
=> [FIX] encourage 멘트 안나오는 문제 수정

iz/src/main/resources/static/js/mainScript.js
=> [FIX] 메인페이지 캘린더 날짜 오류 수정
